version: '3'
services:
  dating_bot_telegram:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    restart: always